= text expressions

Expressions are how parse extracts data from a line of text.
The simplest expression is just a java regular expression pattern.
```yaml
  pattern: ".*"
```
This would match any line of text but would not extract data.
A more useful expression would include named capture groups to extract data.
```yaml
  pattern: "(?<line>.*)"
```
The expression will now save the line of text under the `line` key in the resulting json object.
```javascript
{ line: "..." }
```

Expression patterns will match to any part of the input line unless the pattern includes the `^` or `$` characters.
If a file has the following line of text:
```
name=jane/class=math/
```
Then `class=(?<class>[^/]+)` will match the input line because the pattern was found in the line but
`^class=(?<class>[^/]+)` will not match because class is not at the start of the line.

There are several more options to control how an expression updates the resulting json and modifies the line of text from the file.
Before we discuss other control options, it can be helpful to name expressions.
```yaml
  name: example
  pattern: "(?<line>.*)"
```

== Controlling expressions

per
