= parse User's Guide
:revnumber: {project-version}
:example-caption!:
:sectnums:

== Introduction

parse is a line based text parser to create json from logs and data files.


== Quickstart

1. Download the latest https://github.com/Hyperfoil/parse/releases[release]
2. run the jar against a folder or archive of files. This uses the default parsers.
....
java -jar parse.jar -b /tmp/archive.tar.gz
....
3. We can also use custom parser rules in a yaml
....
cat > rules.yaml << 'EOF'
---
name: mustgather
path: ".*mustgather*.tar.gz"
nest: files.mustgather
asPath: |
  (path)=>({name: path.substring(path.lastIndexOf("/")+1) })
EOF
---

java -jar parse.jar -r rules.yaml -b /tmp/archive.tar.gz
....

== How it works

parse works in 3 phases.

1. Match files to parsers based on file name, file path, and optional header lines.
2. Apply the parser rules to create a json object.
3. Merge the json based on the `nest` path.

== Parser rules
file parser rules (file rules) tell parse how to handle the file content.
The valid rules are:

- link:./reference/asContent.adoc[asContent] - load the entire file content as a string
- asJbossCli - parse the jboss-cli output into json
- asJson - assume the file contains json
- link:./reference/asText.adoc[asText] - parse each line of text
- link:./reference/asPath.adoc[asPath] - execute a javascript function on the file path
- asXml - assume the file contains xml



